Install tensor

In [3]:
pip install tensorflow

In [1]:
import tensorflow as tf
print(tf.__version__)

2.19.0


Create tensor

In [9]:
#scaler tensor
a= tf.constant(5)
print(a)

#1d tensor
v=tf.constant([1,2,3,4])
print(v)

#2d tensor
m=tf.constant([[1,2],[3,4]])
print(m)

#3D tensor
t3= tf.constant([
 [[1, 2], [3, 4]],[[5, 6], [7, 8]]
])
print(t3)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


Tensor Addition

In [8]:
a= tf.constant([10,20,30])
b= tf.constant([1,2,3])
print(a+b)


tf.Tensor([11 22 33], shape=(3,), dtype=int32)


checking datatype and shape of tensor

In [15]:
x = tf.constant([1, 2, 3])
print(x.dtype, x.shape, tf.rank(x))

<dtype: 'int32'> (3,) tf.Tensor(1, shape=(), dtype=int32)


numpy array to tensor

In [16]:
import numpy as np
np_array= np.array(([1,2,3],[4,5,6]))

tensor= tf.convert_to_tensor(np_array)
print(tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int64)
